[package]
name = "ch02_multithread_mandelbrot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
image = "0.20.1"
crossbeam = "0.8.4"   # concurrency
